# -*- coding: utf-8 -*-
"""
paises.py — Traducción de países (como vienen en Wyscout, en inglés) al español.
No necesita internet ni librerías. Si falta alguno, agrégalo en config.py
(TRADUCCION_PAISES) y saldrá avisado en reporte_build.txt.
"""
PAISES = {
    # --- Norte, Centro América y Caribe ---
    "Mexico": "México", "United States": "EE. UU.", "USA": "EE. UU.", "United States of America": "EE. UU.",
    "Canada": "Canadá", "Guatemala": "Guatemala", "Honduras": "Honduras", "El Salvador": "El Salvador",
    "Nicaragua": "Nicaragua", "Costa Rica": "Costa Rica", "Panama": "Panamá", "Belize": "Belice",
    "Cuba": "Cuba", "Jamaica": "Jamaica", "Haiti": "Haití", "Dominican Republic": "República Dominicana",
    "Puerto Rico": "Puerto Rico", "Trinidad and Tobago": "Trinidad y Tobago", "Trinidad & Tobago": "Trinidad y Tobago",
    "Barbados": "Barbados", "Bahamas": "Bahamas", "Grenada": "Granada", "Guyana": "Guyana", "Suriname": "Surinam",
    "Curaçao": "Curazao", "Curacao": "Curazao", "Aruba": "Aruba", "Bermuda": "Bermudas", "Martinique": "Martinica",
    "Guadeloupe": "Guadalupe", "French Guiana": "Guayana Francesa", "Saint Kitts and Nevis": "San Cristóbal y Nieves",
    "Saint Lucia": "Santa Lucía", "Saint Vincent and the Grenadines": "San Vicente y las Granadinas",
    "Antigua and Barbuda": "Antigua y Barbuda", "Dominica": "Dominica", "Montserrat": "Montserrat",
    "Cayman Islands": "Islas Caimán", "Turks and Caicos Islands": "Islas Turcas y Caicos",
    "British Virgin Islands": "Islas Vírgenes Británicas", "US Virgin Islands": "Islas Vírgenes de EE. UU.",
    "Anguilla": "Anguila", "Sint Maarten": "San Martín", "Bonaire": "Bonaire",
    # --- Sudamérica ---
    "Argentina": "Argentina", "Brazil": "Brasil", "Uruguay": "Uruguay", "Paraguay": "Paraguay",
    "Chile": "Chile", "Bolivia": "Bolivia", "Peru": "Perú", "Ecuador": "Ecuador", "Colombia": "Colombia",
    "Venezuela": "Venezuela",
    # --- Europa ---
    "Spain": "España", "Portugal": "Portugal", "France": "Francia", "Italy": "Italia", "Germany": "Alemania",
    "England": "Inglaterra", "Scotland": "Escocia", "Wales": "Gales", "Northern Ireland": "Irlanda del Norte",
    "United Kingdom": "Reino Unido", "Great Britain": "Gran Bretaña", "Republic of Ireland": "Irlanda",
    "Ireland": "Irlanda", "Netherlands": "Países Bajos", "Holland": "Países Bajos", "Belgium": "Bélgica",
    "Luxembourg": "Luxemburgo", "Switzerland": "Suiza", "Austria": "Austria", "Liechtenstein": "Liechtenstein",
    "Denmark": "Dinamarca", "Sweden": "Suecia", "Norway": "Noruega", "Finland": "Finlandia", "Iceland": "Islandia",
    "Faroe Islands": "Islas Feroe", "Poland": "Polonia", "Czech Republic": "República Checa", "Czechia": "Chequia",
    "Slovakia": "Eslovaquia", "Hungary": "Hungría", "Romania": "Rumania", "Bulgaria": "Bulgaria",
    "Greece": "Grecia", "Turkey": "Turquía", "Türkiye": "Turquía", "Cyprus": "Chipre", "Malta": "Malta",
    "Croatia": "Croacia", "Serbia": "Serbia", "Slovenia": "Eslovenia", "Bosnia and Herzegovina": "Bosnia y Herzegovina",
    "Bosnia-Herzegovina": "Bosnia y Herzegovina", "Montenegro": "Montenegro", "North Macedonia": "Macedonia del Norte",
    "Macedonia": "Macedonia del Norte", "FYR Macedonia": "Macedonia del Norte", "Albania": "Albania",
    "Kosovo": "Kosovo", "Russia": "Rusia", "Ukraine": "Ucrania", "Belarus": "Bielorrusia", "Moldova": "Moldavia",
    "Lithuania": "Lituania", "Latvia": "Letonia", "Estonia": "Estonia", "Georgia": "Georgia", "Armenia": "Armenia",
    "Azerbaijan": "Azerbaiyán", "Kazakhstan": "Kazajistán", "Andorra": "Andorra", "San Marino": "San Marino",
    "Monaco": "Mónaco", "Gibraltar": "Gibraltar", "Israel": "Israel",
    # --- África ---
    "Morocco": "Marruecos", "Algeria": "Argelia", "Tunisia": "Túnez", "Libya": "Libia", "Egypt": "Egipto",
    "Senegal": "Senegal", "Gambia": "Gambia", "Guinea": "Guinea", "Guinea-Bissau": "Guinea-Bisáu",
    "Equatorial Guinea": "Guinea Ecuatorial", "Mali": "Malí", "Mauritania": "Mauritania", "Burkina Faso": "Burkina Faso",
    "Niger": "Níger", "Nigeria": "Nigeria", "Ghana": "Ghana", "Côte d'Ivoire": "Costa de Marfil",
    "Cote d'Ivoire": "Costa de Marfil", "Ivory Coast": "Costa de Marfil", "Liberia": "Liberia",
    "Sierra Leone": "Sierra Leona", "Togo": "Togo", "Benin": "Benín", "Cameroon": "Camerún", "Gabon": "Gabón",
    "Congo": "Congo", "Congo DR": "RD Congo", "DR Congo": "RD Congo", "Democratic Republic of the Congo": "RD Congo",
    "Central African Republic": "República Centroafricana", "Chad": "Chad", "Sudan": "Sudán",
    "South Sudan": "Sudán del Sur", "Ethiopia": "Etiopía", "Eritrea": "Eritrea", "Somalia": "Somalia",
    "Djibouti": "Yibuti", "Kenya": "Kenia", "Uganda": "Uganda", "Tanzania": "Tanzania", "Rwanda": "Ruanda",
    "Burundi": "Burundi", "Angola": "Angola", "Zambia": "Zambia", "Zimbabwe": "Zimbabue", "Malawi": "Malaui",
    "Mozambique": "Mozambique", "Madagascar": "Madagascar", "Mauritius": "Mauricio", "Comoros": "Comoras",
    "Seychelles": "Seychelles", "South Africa": "Sudáfrica", "Namibia": "Namibia", "Botswana": "Botsuana",
    "Lesotho": "Lesoto", "Eswatini": "Esuatini", "Swaziland": "Esuatini", "Cape Verde": "Cabo Verde",
    "Cape Verde Islands": "Cabo Verde", "Cabo Verde": "Cabo Verde", "São Tomé and Príncipe": "Santo Tomé y Príncipe",
    "Sao Tome and Principe": "Santo Tomé y Príncipe", "Réunion": "Reunión", "Reunion": "Reunión", "Mayotte": "Mayotte",
    # --- Asia y Oceanía ---
    "Japan": "Japón", "Korea Republic": "Corea del Sur", "South Korea": "Corea del Sur", "Korea DPR": "Corea del Norte",
    "North Korea": "Corea del Norte", "China PR": "China", "China": "China", "Chinese Taipei": "China Taipéi",
    "Taiwan": "Taiwán", "Hong Kong": "Hong Kong", "Macau": "Macao", "Mongolia": "Mongolia",
    "Philippines": "Filipinas", "Indonesia": "Indonesia", "Malaysia": "Malasia", "Singapore": "Singapur",
    "Thailand": "Tailandia", "Vietnam": "Vietnam", "Myanmar": "Myanmar", "Cambodia": "Camboya", "Laos": "Laos",
    "India": "India", "Pakistan": "Pakistán", "Bangladesh": "Bangladés", "Sri Lanka": "Sri Lanka", "Nepal": "Nepal",
    "Afghanistan": "Afganistán", "Iran": "Irán", "IR Iran": "Irán", "Iraq": "Irak", "Syria": "Siria",
    "Lebanon": "Líbano", "Jordan": "Jordania", "Palestine": "Palestina", "Saudi Arabia": "Arabia Saudita",
    "Qatar": "Catar", "United Arab Emirates": "Emiratos Árabes Unidos", "Bahrain": "Baréin", "Kuwait": "Kuwait",
    "Oman": "Omán", "Yemen": "Yemen", "Uzbekistan": "Uzbekistán", "Kyrgyzstan": "Kirguistán",
    "Tajikistan": "Tayikistán", "Turkmenistan": "Turkmenistán", "Australia": "Australia",
    "New Zealand": "Nueva Zelanda", "Fiji": "Fiyi", "Papua New Guinea": "Papúa Nueva Guinea",
    "New Caledonia": "Nueva Caledonia", "Tahiti": "Tahití", "Solomon Islands": "Islas Salomón",
    "Vanuatu": "Vanuatu", "Samoa": "Samoa", "Tonga": "Tonga", "Guam": "Guam",
}
